# -*- coding: utf-8 -*-
"""Gabriela Silveira.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15_DZCyzOsdMFjLUOKEtOkFLuNNhObtCD
"""

MediaTempMaxima = 0
QtdMesesEscaldantes = 0
MesMaisEscaldante = 0
MesMenosQuente = 0
TotalMeses = 12


for mes in range(1,13):
  print(f'Mês {mes}: ', end = '')
  TempMaxima= float(input())

  if mes == 1: mes = 'janeiro'
  if mes == 2: mes = 'fevereiro'
  if mes == 3: mes = 'março'
  if mes == 4: mes = 'abril'
  if mes == 5: mes = 'maio'
  if mes == 6: mes = 'junho'
  if mes == 7: mes = 'julho'
  if mes == 8: mes = 'agosto'
  if mes == 9: mes = 'setembro'
  if mes == 10: mes = 'outubro'
  if mes == 11: mes = 'novembro'
  if mes == 12: mes = 'dezembro'

# Validando os valores:

  while TempMaxima <-60 or TempMaxima >50:
    print('Valor inválido. Redigite a temperatura')
    TempMaxima = float(input())



  # a) Temperatura média maxima anual:

  MediaTempMaxima += TempMaxima
  media = MediaTempMaxima / TotalMeses

  # b) Quantidade de meses escaldantes:

  if TempMaxima>38:
    QtdMesesEscaldantes += 1

  # c) Mês mais escaldante do ano:

  if TempMaxima>MesMaisEscaldante:
    MesMaisEscaldante = TempMaxima



  # d) Mês menos quente do ano:

  if MesMenosQuente == 0 or MesMenosQuente > TempMaxima:
    MesMenosQuente = TempMaxima


print('-----------------------------------------------------------')

print(f'Soma das temperaturas: {MediaTempMaxima} ºC')
print(f'Temperatura média máxima anual: {media} ºC')
print('Quantidade de meses escaldantes: ', QtdMesesEscaldantes)
print(f'O mês mais escaldante foi {mes}: {MesMaisEscaldante} ºC' )
print(f'O mês menos quente foi {mes} :  {MesMenosQuente} ºC')
